### ISSUE TITLE
Randomize the look of the crate a bit

### ISSUE THREAD

**Issue by milivojm** [JamesTheClarke/Arma3-PvP-Missions#2]
Dynamically created crate has to be randomized in content. Randomize what predesignated gear-load outs will spawn in the crates (sniper rifles with fitting ammo, IEDs, Mines, several AKs, RPGs etc.) Basically a variety of hidden cache load-out variants like this is a sniper cache, this is an IED cache etc.

**Comment by milivojm** [comment]
I'll put some type examples here, fill in the list when you can:

1. Assault rifles cache
2. Explosives cache
3. Sniper rifles cache
4. Launcher cache
5. MG cache

Considering it's easier to export loadouts from Virtual Arsenal and then just copy paste the class names, I suggest cache loadouts could be an array of [className, amount] entries. Multiple variants for same cache type could be made and then randomly picked by script.

Is that ok?

**Comment by JamesTheClarke** [comment]
That looks perfect mate!
