### ISSUE TITLE
Create civilian modules

### ISSUE THREAD

**Issue by JamesTheClarke** [JamesTheClarke/Arma3-PvP-Missions#5]
A civilian module has to be created that spawns the correct range of civilians at all three locations. Appropriate flee and patrol modules have to be set to create the illusion of an active town for OpFor to blend in.

**Comment by milivojm** [comment]
Look for Civilian presence module in Ambient category.

**Comment by JamesTheClarke** [comment]
Yeah, already used it for a couple of missions in the past. Made the issue mainly to keep track of things I still need to add and test. ;)
