### ISSUE TITLE
Create first draft on the scenario rules

### ISSUE THREAD

**Issue by JamesTheClarke** [JamesTheClarke/Arma3-PvP-Missions#8]
This mission will involve a certain amount of roleplay. Write down the respective RP rules to facilitate gameplay. Keep them simple and avoid interpretational language.

- add rules to the mission briefing modules
- add rules to the wiki page describing the mission

**Comment by JamesTheClarke** [comment]
First draft is live on the wiki: https://github.com/JamesTheClarke/Arma3-PvP-Missions/wiki/Crimson-Jupiter

**Comment by milivojm** [comment]
Nice, all feasible. As far as I am concerned, you can close this.
